### ISSUE TITLE
Linux build instruction

### ISSUE THREAD

**Issue by AnandSingh** [KilianKegel/EDK2020-MinnowBoard#1]
Hi 

Can you provide a linux build instruction ? or can you guide me how to enable build inlinux system .

Thanks
Anand

**Comment by KilianKegel** [comment]
Hi Anand,

currently I am implementing Linux .ELF x86-64 support for https://github.com/KilianKegel/Visual-ANSI-C-for-UEFI-Shell/tree/Linux
but this is still alpha/experimental.

And you need to setup your PC appropriatly https://github.com/KilianKegel/HowTo-setup-an-UEFI-Development-PC#howto-setup-an-uefi-development-pc, step 1,2 and 16

Cheers,
Kilian

**Comment by AnandSingh** [comment]
Thanks Kilan, appriciate your help. I will take a look for windows development setup. 

I have a custom board with 4GB of memory, can you guide me where shall I change so that it will reflect the 4GB RAM in UEFI bios.

-Anand

**Comment by KilianKegel** [comment]
Absolutely: NO.

Von: Anand Singh<mailto:notifications@github.com>
Gesendet: Friday, November 20, 2020 9:18 PM
An: KilianKegel/EDK2020-MinnowBoard<mailto:EDK2020-MinnowBoard@noreply.github.com>
Cc: KilianKegel<mailto:kilian_kegel@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Betreff: Re: [KilianKegel/EDK2020-MinnowBoard] Linux build instruction (#1)


Thanks Kilan, appriciate your help. I will take a look for windows development setup.

I have a custom board with 4GB of memory, can you guide me where shall I change so that it will reflect the 4GB RAM in UEFI bios.

-Anand

**Comment by AnandSingh** [comment]
was able to build with windows env and also created a linux dev setup
